config/routes.rb
Rails.application.routes.draw do
  resources :coupons

  resources :line_items

  resources :carts

  ActiveAdmin.routes(self)
  devise_for :users,
             :controllers => {
               omniauth_callbacks: 'users/omniauth_callbacks',
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             }

  resources :admin_contacts

  resources :hobbies_interests

  resources :countries

  resources :categories

  resources :advertisements

  # Dashboard
  get 'dashboard', to: 'dashboard#index', as: :user_root
  get 'dashboard/edit_profile', format: 'js'
  put 'dashboard/update_profile', format: 'js'

  resources :templates do
    member do
      get 'details'
      get 'activate'
      get 'add_to_my'
      delete 'remove_from_my'
    end
  end

  resources :languages

  resources :references

  resources :skills

  resources :experiences

  resources :educations

  resources :overviews

  root 'home#index'
  get 'home/load_states'
  get '/privacy-policy' => 'home#privacy_policy', as: :privacy_policy
  get 'terms-of-use' => 'home#terms_of_use', as: :terms_of_use
  get 'email-resume' => 'home#email_resume', as: :email_resume

  # sitemaps url
  get 'sitemap.xml' => 'home#sitemap', format: :xml, as: :sitemap
  get 'sitemaps/site.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'site' }
  get 'sitemaps/public_profiles.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'public_profiles' }
  get 'sitemaps/published_templates.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'published_templates' }
  get 'blog-sitemap.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'blog/sitemap' }
  get 'sitemaps/blog/site.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'blog/site' }
  get 'sitemaps/blog/blog_posts.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'blog/blog_posts' }
  get 'robots.txt' => 'home#robots', format: :text

  #tag url
  get 'tags/:tag', to: 'profiles#tag', as: :tag

  #send resume by email popover link
  get 'send-resume-by-email' => 'home#send_resume_by_email'

  # subscribe email to mailchimp
  post 'subscribe' => 'home#subscribe'

  # it must be placed in end of file, as path: ''
  resources :profiles, except: [:index, :destroy], path: '' do
    member do
      put 'update_profile_photo'
      put 'update_username'
    end

    collection do
      get 'set_objective'
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'public', only: [:index]

  def index
    redirect_to user_root_path  if user_signed_in?

    @top_users = User.top_users
  end

  def load_states
    @country_code = params[:country_code]

    respond_to do |format|
      format.js
    end
  end

  def privacy_policy

  end

  def terms_of_use

  end

  def sitemap
    file_name = params[:file_name].present? ? params[:file_name] : 'sitemap'
    path = Rails.root.join('public', 'sitemaps', "#{file_name}.xml")
    if File.exists?(path)
      render xml: open(path).read
    else
      render text: 'Sitemap not found.', status: :not_found
    end
  end

  def robots
  end

  def send_resume_by_email
    if params[:email][:subject].present? && params[:email][:receiver].present? && params[:email][:body].present?
      from = current_user.present? ? current_user.email : params[:email][:sender]
      SendResume.email_resume(from, params[:email][:receiver], params[:email][:subject], params[:email][:body]).deliver
      redirect_to root_path, :notice => "Email Sent successfully!"
    else
      redirect_to root_path, :notice => "Mandatory fields cannot remain blank!"
    end
  end

  def subscribe
    gb = Gibbon::API.new(CONFIG[:mailchimp_api_key])
    gb.lists.subscribe({:id => CONFIG["#{site_name}_subscribers_list_id".to_sym], :email => {:email => params[:email]}, :double_optin => false})
    Rails.logger.info "------------------- #{gb.inspect} -------------------"
    flash.now[:success] = 'Your email address added successfully'
  rescue
    flash.now[:error] = 'Failed to add your email address'
  end
end

app/views/home/_index_contact.html.erb
<!-- BEGIN DIV #CONTACT -->
<div id="contact">

  <!-- Div #contact title -->
  <h1 class="wow bounceIn" data-wow-offset="100">Get in <strong>touch</strong> with us</h1>

  <!-- Container colored line -->
  <div class="container-colored-line wow bounceIn" data-wow-offset="200">

    <!-- Colored line -->
    <hr class="colored-line">

    <!-- Additional line -->
    <div class="add-colored-line"></div>

  </div><!-- end of div .container-colored-line -->

  <!-- Div #contact description -->
  <em class="wow fadeInDown" data-wow-offset="200">Any feedback? Sure! Just fill the form and let us hear you.</em>

  <!-- Begin form. You can change the action attribute to your PHP file name -->
  <%= form_for AdminContact.new, html: { id: 'contact-form', class: 'contact-form wow bounceIn', data: { wow_offset: 200 } }, remote: true do |f| %>

    <!-- Input name -->
    <div class="col-md-6 col-lg-6">
      <%= f.text_field :name, required: true, placeholder: 'Name' %>
    </div>

    <!-- Input email -->
    <div class="col-md-6 col-lg-6">
      <%= f.email_field :email, required: true, placeholder: 'Email Address' %>
    </div>

    <!-- Input subject -->
    <div class="col-md-12 col-lg-12 col-sm-12">
      <%= f.text_field :title, required: true, placeholder: 'Subject' %>
    </div>

    <!-- Input message -->
    <div class="col-md-12 col-lg-12 col-sm-12">
      <%= f.text_area :body, required: true, placeholder: 'Your message' %>
    </div>

    <!-- Input submit -->
    <p>
      <%= f.submit 'Send Message' %>
    </p>
    <%= f.hidden_field :category, value: AdminContact::CATEGORIES[:other] %>
  <% end %>
  <!-- end of form -->

</div>
<!-- END OF DIV #CONTACT -->

app/views/home/_index_describe.html.erb
<!-- BEGIN DIV #DESCRIBE -->
<div class="brief" id="describe">

  <!-- Begin div .row -->
  <div class="row">

    <!-- Div #why - left column -->
    <div class="col-md-6 col-lg-6 left-column">
      <h1 class="title wow fadeInLeft" data-wow-offset="150"><strong>Let</strong> the smart career start with the smart <%= t("#{site_name}.main_keyword") %></h1>

      <!-- Container colored line two -->
      <div class="container-colored-line-two wow bounceInLeft" data-wow-offset="170">

        <!-- colored line two -->
        <hr class="colored-line-two">

        <!-- additional colored line two -->
        <div class="add-colored-line-two"></div>
      </div><!-- end of container colored line two -->

      <!-- Div #describe description -->
      <em class="description wow fadeInDown" data-wow-delay=".2s" data-wow-offset="150">Present your <%= t("#{site_name}.main_keyword") %> with <%= t("#{site_name}.site_name") %><br></em>

      <!-- Div .container-item wraps 3 items, contains icon and text description -->
      <div class="container-item">
        <!-- First item of div #why -->
        <div class="item">
          <div class="icon icon-heart wow bounceIn" data-wow-offset="150"></div>
          <p class="item-description wow fadeInRight" data-wow-offset="150">
            Build <%= t("#{site_name}.main_keyword") %><br>
            A catchy <%= t("#{site_name}.main_keyword") %> in just 5 minutes<br>
          </p>
        </div><!-- end of first item -->

        <!-- Second item -->
        <div class="item">
          <div class="icon icon-thumbsup wow bounceIn" data-wow-offset="150"></div>
          <p class="item-description wow fadeInRight" data-wow-offset="150">
            Choose your free <%= t("#{site_name}.main_keyword") %> template<br>
            We provide creative and modern <%= t("#{site_name}.main_keyword") %> templates that can make a difference
          </p>
        </div><!-- end of second item -->

        <!-- Third item -->
        <div class="item">
          <div class="icon icon-help wow bounceIn" data-wow-offset="150"></div>
          <p class="item-description wow fadeInRight" data-wow-offset="150">
            Share <%= t("#{site_name}.main_keyword") %> easily<br>
            Have a handy <%= t("#{site_name}.main_keyword") %> URL and share it across the World Wide Web
          </p>
        </div><!-- end of third item -->

        <!-- Fourth item -->
        <div class="item">
          <div class="icon icon-arrow wow bounceIn" data-wow-offset="150"></div>
          <p class="item-description wow fadeInRight" data-wow-offset="150">
            Grow smart career<br>
            Connect with others through the <%= t("#{site_name}.main_keyword") %> URL!
          </p>
        </div><!-- end of fourth item -->

        <div class="container-other-download  wow bounceInLeft" data-wow-offset="150">
          <a href="<%= templates_path %>" class="learn"><%= t("#{site_name}.main_key") %> Templates + </a>
          <a href="<%= new_user_session_path %>" class="get">Make <%= t("#{site_name}.main_key") %></a>
        </div>

      </div><!-- end of div .container-item -->

    </div><!-- end of div #describe - right column -->

    <!-- Container why phone wraps two mockup phones -->
    <div class="col-md-6 col-lg-6 container-phones right-column">

      <!-- The second phone mockup -->
      <div class="wow bounceInRight" data-wow-offset="150" data-wow-delay=".35s" data-wow-duration="1.2s">
        <%= image_tag 'mockup/third-phone.png', alt: 'Apps mockup', class: 'second-phone', id: 'describe-second-phone' %>
      </div>

      <!-- The first phone mockup -->
      <div class="wow bounceInRight" data-wow-offset="150" data-wow-duration="1.2s">
        <%= image_tag 'mockup/third-phone.png', alt: 'Apps mockup', class: 'first-phone', id: 'describe-first-phone' %>
      </div>

    </div><!-- end of container-phones -->

  </div><!-- end of div .row -->

</div>
<!-- END OF DIV #DESCRIBE -->

app/views/home/_index_downloads.html.erb
<!-- BEGIN DIV #DOWNLOADS -->
<div id="downloads">

  <div class="background-solid">

    <h1 class="wow bounceIn" data-wow-offset="100">Experience <strong>soon</strong>!</h1>

    <div class="container-downloads wow fadeInUp" data-wow-offset="100">

      <p class="centering">
        <a href="#" target="_blank" class="windows">
          <%= image_tag 'download_on_the_app_store2_150x36px_.png', alt: 'Windows store button' %>
        </a>
      </p>

      <span class="other">or</span>

      <p class="centering">
        <a href="#" target="_blank" class="android">
          <%= image_tag 'buttons/google-play.png', alt: 'Google play button' %>
        </a>
      </p>
    </div>

  </div>

</div>

app/views/home/_index_features.html.erb
<!-- BEGIN OF DIV #FEATURES -->
<div id="features" class="features">

  <!-- Div #features title -->
  <h1 class="wow bounceIn" data-wow-offset="100"><strong>Free</strong> <%= t("#{site_name}.main_keyword") %> Builder</h1>

  <!-- Container colored line -->
  <div class="container-colored-line wow bounceIn" data-wow-offset="200">

    <!-- Colored line -->
    <hr class="colored-line">

    <!-- Additional colored line -->
    <div class="add-colored-line"></div>

  </div><!-- End of container colored line -->

  <!-- Div #features description -->
  <em class="wow fadeInDown" data-wow-delay=".3s" data-wow-offset="200">Awesome features to present  you a optimal <%= t("#{site_name}.main_key") %>.</em>

  <!-- BEGIN DIV .CONTAINER-COLUMN -->
  <div class="row container-column">
    <!-- Div #features - top column -->
    <div class="col-md-12 col-lg-12 top-column wow bounceInLeft">
      <div class="col-md-4">
        <div class="fa fa-upload"></div>
        <h4>Easy Upload</h4>
        <em>Use the free <%= t("#{site_name}.main_keyword") %> builder to create <%= t("#{site_name}.main_keyword") %> in less than 5 minutes</em>
      </div>

      <div class="col-md-4">
        <div class="fa fa-link"></div>
        <h4>Friendly url</h4>
        <em><%= t("#{site_name}.home_main_title") %> provides web URL for your <%= t("#{site_name}.main_keyword") %></em>
      </div>

      <div class="col-md-4">
        <div class="icon icon-sun2"></div>
        <h4><%= t("#{site_name}.main_key") %> templates</h4>
        <em>Choose among numerous eye catching modern <%= t("#{site_name}.main_keyword") %> templates</em>
      </div>
    </div><!-- end of div #features left column -->

    <!-- *************************** -->

    <!-- Div #features - bottom column -->
    <div class="col-md-12 col-lg-12 bottom-column wow bounceInRight">
      <div class="col-md-4">
        <div class="icon icon-mobile"></div>
        <h4>Responsive design</h4>
        <em>Now your <%= t("#{site_name}.main_keyword") %> will be visible on multiple devices</em>
      </div>

      <div class="col-md-4">
        <div class="icon icon-eye"></div>
        <h4>Easy share</h4>
        <em>You can share your <%= t("#{site_name}.main_key") %> via email & social media. Isn’t it fantastic?</em>
      </div>

      <div class="col-md-4">
        <div class="fa fa-download"></div>
        <h4>Download pdf</h4>
        <em><%= t("#{site_name}.home_main_title") %> lets your <%= t("#{site_name}.main_key") %> viewer to download it as PDF from anywhere</em>
      </div>
    </div><!-- end of div #features left column -->
  </div>
  <!-- END OF DIV .CONTAINER-COLUMN -->
</div>
<!-- END OF DIV #FEATURES -->

app/views/home/_index_pricing.html.erb
<!-- BEGIN DIV #PRICING-TABLE -->
<div id="pricing-table">

  <!-- Div #pricing-table title -->
  <h1 class="wow bounceIn" data-wow-offset="100">New - <strong>Pricing Table</strong></h1>

  <!-- Container colored line -->
  <div class="container-colored-line wow bounceIn" data-wow-offset="200">

    <!-- Colored line -->
    <hr class="colored-line">

    <!-- Additional line -->
    <div class="add-colored-line"></div>

  </div><!-- end of div .container-colored-line -->

  <!-- Div #pricing-table description -->
  <em class="description wow fadeInDown" data-wow-offset="200">Now you have responsive pricing table.</em>

  <div class="container-table">

    <!-- table 1 -->
    <div class="pricing wow fadeInRight table-1" data-wow-offset="400" data-wow-delay=".2s">
      <h3>Personal</h3>
      <div class="price-container row">
        <div class="col-md-12 dollar">$50</div>
        <div class="col-md-12 per-month">/ MONTH</div>
      </div>
      <em class="detail-price">Little description about this.</em>
      <ul class="price-features">
        <li>
          <span class="feature">Feature #1</span>
          <span class="check icon-checkmark"></span>
        </li>
        <li>
          <span class="feature">Feature #2</span>
          <span class="check icon-checkmark"></span>
        </li>
        <li>
          <span class="feature">Feature #3</span>
          <span class="cross icon-cross"></span>
        </li>
        <li>
          <span class="feature">Feature #4</span>
          <span class="cross icon-cross"></span>
        </li>
      </ul>
      <a class="order" href="#">Order Now!</a>

    </div><!-- end of table 1 -->

    <!-- table 2 -->
    <div class="pricing wow bounceIn" data-wow-offset="300">
      <h3>Proffesional</h3>
      <div class="price-container row">
        <div class="col-md-12 dollar">$80</div>
        <div class="col-md-12 per-month">/ MONTH</div>
      </div>
      <em class="detail-price">Little description about this.</em>
      <ul class="price-features">
        <li>
          <span class="feature">Feature #1</span>
          <span class="check icon-checkmark"></span>
        </li>
        <li>
          <span class="feature">Feature #2</span>
          <span class="check icon-checkmark"></span>
        </li>
        <li>
          <span class="feature">Feature #3</span>
          <span class="check icon-checkmark"></span>
        </li>
        <li>
          <span class="feature">Feature #4</span>
          <span class="check icon-checkmark"></span>
        </li>
      </ul>
      <a class="order" href="#">Order Now!</a>

    </div><!-- end of table 2 -->

    <!-- table 3 -->
    <div class="pricing wow fadeInLeft table-3" data-wow-offset="400" data-wow-delay=".2s">
      <h3>Business</h3>
      <div class="price-container row">
        <div class="col-md-12 dollar">$60</div>
        <div class="col-md-12 per-month">/ MONTH</div>
      </div>
      <em class="detail-price">Little description about this.</em>
      <ul class="price-features">
        <li>
          <span class="feature">Feature #1</span>
          <span class="check icon-checkmark"></span>
        </li>
        <li>
          <span class="feature">Feature #2</span>
          <span class="check icon-checkmark"></span>
        </li>
        <li>
          <span class="feature">Feature #3</span>
          <span class="check icon-checkmark"></span>
        </li>
        <li>
          <span class="feature">Feature #4</span>
          <span class="cross icon-cross"></span>
        </li>
      </ul>
      <a class="order" href="#">Order Now!</a>

    </div><!-- end of table 3 -->

  </div>

</div>
<!-- END OF DIV ##PRICING-TABLE -->

app/views/home/_index_screenshot.html.erb
<!-- BEGIN DIV #SCREENSHOT -->
<div id="screenshot">

  <!-- Div #screenshot title -->
  <h1 class="wow bounceIn" data-wow-offset="100">Free <%= t("#{site_name}.main_key") %> Templates</h1>

  <!-- Container colored line -->
  <div class="container-colored-line wow bounceIn" data-wow-offset="200">

    <!-- Colored line -->
    <hr class="colored-line">

    <!-- Additional colored line -->
    <div class="add-colored-line"></div>

  </div><!-- end of div .container-colored-line -->

  <!-- Div #screenshot description -->
  <em class="wow fadeInDown" data-wow-offset="200">Numerous modern, functional and creative <%= t("#{site_name}.main_keyword") %> templates</em>

  <div class="container">

    <!-- Screenshot main container, using owl carousel and nivo lightbox -->
    <div id="owl-container-screenshot" class="owl-carousel">
      <!-- Div #screenshot item -->

      <!--show templates on home page-->
      <% UserTemplate.select(:template_id).uniq.collect{|t| t.template}.each do |template| %>
        <!--<div class="item">-->
        <div class="itemofcarousel">
          <%= link_to image_tag(template.image.url(:thumb), alt: 'Screenshot Image'), template_path(template) %>
        </div>
      <% end %>
      <!--show templates on home page-->

      <!--<div class="item">-->
        <%#= link_to image_tag('ss/1.png', alt: 'Screenshot Image'), image_path('ss/1.png'), class: 'item', data: { lightbox_gallery: 'gallery1' } %>
      <!--</div>-->


    </div><!-- end of div ."owl-container-screenshot -->
  </div>
 <br/>
  <div class="text-center">
    <a href="<%= templates_path %>" class="get"><%= t("#{site_name}.main_key") %> Templates + </a>


  </div>
</div>
<!-- END OF DIV #SCREENSHOT -->

app/views/home/_index_testimonials.html.erb
<!-- BEGIN DIV #TESTIMONIALS -->
<div class="testimonials" id="testimonials">

  <div class="background-solid">

    <div class="row">

      <div class="col-md-12 col-lg-12">

        <!-- Begin div #owl-container-services -->
        <div id="owl-container-testimonials" class="owl-carousel">

          <!-- First item carousel -->
          <div class="item">

            <!-- Container quotes wraps profile photo, name, and quote -->
            <div class="container-quotes">

              <!-- Profile photo -->
              <%= image_tag 'people/1.png', alt: 'People', class: 'profile' %>

              <!-- Div .quotes -->
              <div class="quotes">

                <!-- quote left icon -->
                <sup class="fa fa-quote-left"></sup>

                Lorem ipsum dolor sit amet, consectetur adipisicing elit,<br>
                sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

                <!-- quote right icon -->
                <sup class="fa fa-quote-right"></sup>

              </div><!-- end of quotes -->

              <!-- Profile name -->
              <h3 class="profile-name">togar natio</h3>

              <!-- Profession -->
              <cite>web designer</cite>

            </div><!-- end of container quotes -->

          </div><!-- end of first item carousel -->

          <!-- Second item carousel -->
          <div class="item">

            <div class="container-quotes">
              <%= image_tag 'people/2.png', alt: 'People', class: 'profile' %>

              <div class="quotes">
                <sup class="fa fa-quote-left"></sup>
                Ut enim ad minim veniam, quis nostrud exercitation<br>
                ullamco laboris nisi ut aliquip ex ea commodo consequat.
                <sup class="fa fa-quote-right"></sup>

              </div>

              <h3 class="profile-name">abdurrahman</h3>
              <cite>web developer</cite>
            </div>

          </div><!-- end of Second item carousel -->

          <!-- Third item carousel -->
          <div class="item">

            <div class="container-quotes">
              <%= image_tag 'people/3.png', alt: 'People', class: 'profile' %>

              <div class="quotes">
                <sup class="fa fa-quote-left"></sup>
                Duis aute irure dolor in reprehenderit in<br>
                voluptate velit esse cillum dolore eu fugiat nulla pariatur.
                <sup class="fa fa-quote-right"></sup>
              </div>

              <h3 class="profile-name">yona sinaga</h3>
              <cite>mobile designer</cite>
            </div>

          </div><!-- end of Third item carousel -->

        </div>
        <!-- end div #owl-container-services -->

      </div>
    </div>

  </div>
  <!-- end of div .background-solid -->

</div>
<!-- END OF DIV #TESTIMONIALS -->

app/views/home/_index_video.html.erb
<!-- BEGIN DIV #VIDEO -->
<div id="video">
  <div class="row">
    <div class="col-md-6 video-iframe wow fadeInLeft" data-wow-offset="300">
      <iframe id="iframe" src="http://player.vimeo.com/video/31211553?title=0&amp;byline=0&amp;portrait=0&amp;color=3498db" width="100%" height="500" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
    </div>

    <div class="col-md-6 details right-column">

      <!-- Div #video title -->
      <h1 class="title wow fadeInRight" data-wow-offset="300">About - <strong><%= t("#{site_name}.home_main_title") %></strong></h1>

      <!-- Container colored line two -->
      <div class="container-colored-line-two wow bounceInRight" data-wow-offset="300">

        <!-- Colored line two -->
        <hr class="colored-line-two">

        <!-- Additional colored line two -->
        <div class="add-colored-line-two"></div>
      </div><!-- end of container colored line two -->

      <!-- Div #why description -->
      <em class="description wow fadeInDown" data-wow-delay=".3s" data-wow-offset="300">
        Sign up today to get your very own professional, creative and modern <%= t("#{site_name}.main_keyword") %>.
      </em>

      <!-- Div .description -->
      <div class="details-container-description">

        <p class="why-description wow fadeInRight" data-wow-offset="300">
          Tired of searching free <%= t("#{site_name}.main_keyword") %> builder that can really work for you? You’ve come to the right place. It’s time
          to put an end to your entire needs as <%= t("#{site_name}.home_main_title") %> is providing free <%= t("#{site_name}.main_keyword") %> builder by using which you can craft
          a <%= t("#{site_name}.main_keyword") %> which can create that everlasting first impression on your employer’s mind. That’s not all, you can take
          advantage of free <%= t("#{site_name}.main_keyword") %> templates with customized URL of your name (Smart, isn’t it?). What all does it takes?
          Just sign up with us, enter your academic skills and professional information, pick a <%= t("#{site_name}.main_keyword") %> template of your own
          choice and you’re ready to get your dream job.
        </p>
        <p class="why-description wow fadeInRight" data-wow-offset="300">
          Share your <%= t("#{site_name}.main_keyword") %> directly with the prospective employer or friend with a  simple URL link. No more hassle of
          creating your own template and attaching it to the E-mail. Drop <%= t("#{site_name}.main_keyword") %> enables you to easily share your <%= t("#{site_name}.main_keyword") %>
          across the World Wide Web, which is viewable on all devices. Last but not the least, anyone can save it as PDF
          or share it further from any device.
        </p>
      </div><!-- end of div .description -->
    </div>
  </div>
</div>

app/views/home/email_resume.html.erb
<div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 n-area-bg" id="send_resume_by_email">
  <legend class="login-now lato-font">Send this resume by email</legend>
  <%= flash_message %>
  <%= form_for current_profile.present? ? current_profile : User.new, {url: send_resume_by_email_path, method: :get, class: "form-horizontal"} do |f| %>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">From(*)</label>
      <div class="col-sm-10">
        <% if current_user.present? %>
          <input type="email" name="email[sender]" value="<%= current_user.email %>" disabled>
        <% else %>
          <input type="email" name="email[sender]">
        <% end %>
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">To(*)</label>
      <div class="col-sm-10">
        <input type="email" name="email[receiver]" >
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Subject(*)</label>
      <div class="col-sm-10">
        <input type="text" name="email[subject]" >
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label">Body(*)</label>
      <div class="col-sm-10">
        <textarea class="wysihtml5" rows="7" id="comment" name="email[body]" ><%= t("dropresume.email_body", :href => link_to(t("dropresume.resume").html_safe, current_user.present? ? profile_url(current_profile) : "")) %></textarea>
      </div>
    </div>

    <div class="form-actions n-field lato-font pull-right">
      <button type="submit" class="btn btn-primary">Send</button>
    </div>
  <% end %>
</div>
<span class="clearfix"></span>

<style>
  #send_resume_by_email{margin-top: 30px; margin-bottom: 30px;}
  #send_resume_by_email input {
    margin-bottom: 10px;
  }
  #send_resume_by_email input, #send_resume_by_email textarea {
    width: 100%;
  }
  .wysihtml5-toolbar .btn-group, .btn-group-vertical{
    display: inline-flex;
  }
  .wysihtml5-toolbar .dropdown-toggle {
    margin-top: 0;
  }
  .wysihtml5-toolbar .btn-default {
    padding: 4px 12px;
  }

</style>
<script type="text/javascript">bkLib.onDomLoaded(nicEditors.allTextAreas);</script>

app/views/home/index.html.erb
<%= render partial: 'home/index_navbar' %>

<div id="main-content" class="fade out">
  <%= render partial: 'home/index_home' %>
  <div id="features-target"></div>
  <%= render partial: 'home/index_features' %>
  <div id="action-target"></div>
  <%= render partial: 'home/index_screenshot' %>
  <%#= render partial: 'home/index_action' %>
  <div id="why-target"></div>
  <%= render partial: 'home/index_video' %>
  <%#= render partial: 'home/index_why' %>
  <div id="describe-target"></div>
  <%= render partial: 'home/index_describe' %>
  <%#= render partial: 'home/index_testimonials' %>
  <div id="most-viewed-resumes"></div>
  <%= render partial: 'home/index_valuable_users' %>
  <div id="screenshot-target"></div>
  <%#= render partial: 'home/index_screenshot' %>
  <%= render partial: 'home/index_services' %>
  <div id="downloads-target"></div>
  <%= render partial: 'home/index_downloads' %>
  <%#= render partial: 'home/index_pricing' %>
  <div id="contact-target"></div>
  <%= render partial: 'home/index_contact' %>
</div>

app/views/home/subscribe.js.erb
<% if flash.now[:error].blank? %>
$('.subscribe-success').css('transform', 'scale(1)');
<% end %>