config/routes.rb
Rails.application.routes.draw do
  resources :coupons

  resources :line_items

  resources :carts

  ActiveAdmin.routes(self)
  devise_for :users,
             :controllers => {
               omniauth_callbacks: 'users/omniauth_callbacks',
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               passwords: 'users/passwords',
               confirmations: 'users/confirmations'
             }

  resources :admin_contacts

  resources :hobbies_interests

  resources :countries

  resources :categories

  resources :advertisements

  # Dashboard
  get 'dashboard', to: 'dashboard#index', as: :user_root
  get 'dashboard/edit_profile', format: 'js'
  put 'dashboard/update_profile', format: 'js'

  resources :templates do
    member do
      get 'details'
      get 'activate'
      get 'add_to_my'
      delete 'remove_from_my'
    end
  end

  resources :languages

  resources :references

  resources :skills

  resources :experiences

  resources :educations

  resources :overviews

  root 'home#index'
  get 'home/load_states'
  get '/privacy-policy' => 'home#privacy_policy', as: :privacy_policy
  get 'terms-of-use' => 'home#terms_of_use', as: :terms_of_use
  get 'email-resume' => 'home#email_resume', as: :email_resume

  # sitemaps url
  get 'sitemap.xml' => 'home#sitemap', format: :xml, as: :sitemap
  get 'sitemaps/site.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'site' }
  get 'sitemaps/public_profiles.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'public_profiles' }
  get 'sitemaps/published_templates.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'published_templates' }
  get 'blog-sitemap.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'blog/sitemap' }
  get 'sitemaps/blog/site.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'blog/site' }
  get 'sitemaps/blog/blog_posts.xml' => 'home#sitemap', format: :xml, defaults: { file_name: 'blog/blog_posts' }
  get 'robots.txt' => 'home#robots', format: :text

  #tag url
  get 'tags/:tag', to: 'profiles#tag', as: :tag

  #send resume by email popover link
  get 'send-resume-by-email' => 'home#send_resume_by_email'

  # subscribe email to mailchimp
  post 'subscribe' => 'home#subscribe'

  # it must be placed in end of file, as path: ''
  resources :profiles, except: [:index, :destroy], path: '' do
    member do
      put 'update_profile_photo'
      put 'update_username'
    end

    collection do
      get 'set_objective'
    end
  end
end

app/models/education.rb
# user_id:integer, title:string, institute:string, location:string, major:string, result:string, description:text,
# start_date:date, end_date:date, created_at:datetime, updated_at:datetime, current:boolean

class Education < ActiveRecord::Base
  # == Include Modules == #
  include ProfileCompleteness

  # == Constants == #

  # == Attributes == #

  # == File Uploader == #

  # == Associations and Nested Attributes == #
  belongs_to :user

  # == Validations == #

  # == Callbacks == #
  after_create :activity_profile_to_facebook
  after_destroy :activity_profile_to_facebook

  # == Scopes and Other macros == #

  # == Instance methods == #

  # == Private == #
  def activity_profile_to_facebook
    self.user.facebook_activity(CONFIG[:host], 'dropresume:update')
  end
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_education, only: [:show, :edit, :update, :destroy]

  respond_to :js

  def index
    @educations = current_user.educations
    respond_with(@educations)
  end

  def show
    respond_with(@education)
  end

  def new
    @education = Education.new
    respond_with(@education)
  end

  def edit
  end

  def create
    @education = Education.new(education_params)
    @education.user = current_user

    if @education.save
      flash.now[:success] = 'New education added successfully.'
    else
      flash.now[:error] = 'Failed to add new education information'
      add_error_messages(@education)
    end
    respond_with(@education)
  end

  def update
    @education.update(education_params)  if @education.user_id == current_user.id
    respond_with(@education)
  end

  def destroy
    @education.destroy  if @education.user_id == current_user.id
    respond_with(@education)
  end

  private
    def set_education
      @education = Education.find(params[:id])
    end

    def education_params
      params.require(:education).permit(:title, :institute, :location, :major, :result, :description, :start_date, :end_date, :current)
    end
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/views/educations/_education_template.html.erb
<%# locals: { education: Education object } %>
<div class="col-lg-12 a-bdr">
  <div class="col-lg-12  bar-bg">
    <div class="col-lg-8 tp-title">
      <h3><%= education.institute %></h3>
      <span><%= "( #{date_format education.start_date} to #{education.current? ? 'current' : date_format(education.end_date) } )" %></span>
    </div>
    <div class="col-lg-4 text-right edit-btn">
      <%= link_to edit_education_path(education), remote: true do %>
          <i class="fa fa-pencil-square"></i>
      <% end %>
      <%= link_to education_path(education), method: :delete, remote: true do %>
          <i class="fa fa-times"></i>
      <% end %>
    </div>
    <div class="col-lg-11 tp-sub-title">
      <%= education.title %>
    </div>
  </div>
  <div class="col-lg-12 pd-area">
    <h4 class="sub-title"><%= education.major %></h4>
    <p><%= education.description %></p>
  </div>
</div>

app/views/educations/_form.html.erb
<%# locals: {education: Education.new or Education.find params[:id]} %>
<%= form_for education, remote: true, authenticity_token: true do |f| %>
  <div class="field-areas">
    <div class="form">
      <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <div class="form-group">
          <%= f.text_field :title, class: 'form-control pull-left fd-tht-size', placeholder: 'Title', required: true,  title: 'Title', rel: 'tooltip' %>
        </div>
      </div>
      <span class="clearfix"></span>

      <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
        <div class="form-group">
          <%= f.text_field :institute, class: 'form-control pull-left fd-size', placeholder: 'Institute', required: true,  title: 'Institute', rel: 'tooltip' %>
        </div>
      </div>
      <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
        <div class="form-group">
          <%= f.text_field :location, class: 'form-control pull-right fd-size', placeholder: 'Location', required: true,  title: 'Location', rel: 'tooltip' %>
        </div>
      </div>
      <span class="clearfix"></span>

      <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
        <div class="form-group">
          <%= f.text_field :major, class: 'form-control pull-left fd-size', placeholder: 'Major', required: true,  title: 'Major', rel: 'tooltip' %>
        </div>
      </div>
      <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
        <div class="form-group">
          <%= f.text_field :result, class: 'form-control pull-right fd-size', placeholder: 'Result',  title: 'Result', rel: 'tooltip' %>
        </div>
      </div>
      <span class="clearfix"></span>

      <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
        <div class="date-form dates">
          <div class="control-group">
            <div class="controls ">
              <div class="input-group">
                <%= f.text_field :start_date, value: education.start_date.try(:strftime, '%d-%m-%Y'), class: 'date-picker form-control txt-sze', placeholder: 'Start Date', required: true,  title: 'Start Date', rel: 'tooltip' %>
                <label for="education_start_date" class="input-group-addon btn">
                  <span class="glyphicon glyphicon-calendar"></span>
                </label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-lg-6 col-sm-6 col-md-6 col-xs-12">
        <div class="date-form dates pull-right">
          <div class="control-group ">
            <div class="controls">
              <div class="input-group">
                <%= f.text_field :end_date, value: education.end_date.try(:strftime, '%d-%m-%Y'), class: 'date-picker form-control txt-sze', placeholder: 'End Date',  title: 'End Date keep blank if continue', rel: 'tooltip' %>
                <label for="education_end_date" class="input-group-addon btn">
                  <span class="glyphicon glyphicon-calendar"></span>
                </label>
                <div class="pull-right till-today">
                  <%= f.check_box :current %>
                  <%= f.label :current, nil, class: 'current-checkbox-label' do %>
                    <span></span> Current
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <span class="clearfix"></span>

      <div class="col-lg-12 col-sm-12 col-md-12 col-xs-12">
        <div class="form-group">
          <%= f.text_area :description, placeholder: 'Write Description Here (Optional)', class: 'form-control',  title: 'Description (Optional)', rel: 'tooltip' %>
        </div>
      </div>
      <span class="clearfix"></span>

      <div class="btn-group pull-right center-xs">
        <%= button_tag type: 'submit', class: 'btn btn-large default-button' do %>
            <i class="fa fa-floppy-o"></i> Save
        <% end %>
        <%= button_tag type: 'reset', class: 'btn btn-large default-button' do %>
            <i class="fa fa-refresh"></i> Reset
        <% end %>
      </div>
      <span class="clearfix"></span>
    </div>
  </div>
<% end %>

app/views/educations/_index.html.erb
<div id="show_educations">
  <% if current_user.educations.present? %>
    <% current_user.educations.each do |education| %>
      <%= render partial: 'educations/education_template', locals: { education: education } %>
    <% end %>
    <div class="btn-group center-xs mar-t20" id="add-new-education">
      <%= link_to new_education_path, class: 'btn btn-large default-button', remote: true do %>
        <i class="fa fa-plus-square"></i> Add New
      <% end %>
    </div>
    <div id="education-form-container" style="clear: both"></div>
  <% else %>
    <div id="education-form-container" style="clear: both"><%= render partial: 'educations/form', locals: {education: Education.new} %></div>
  <% end %>
</div>

app/views/educations/create.js.erb
$('#message_container').html('<%=j render partial: 'shared/flash_message' %>');
//$('html, body').animate({scrollTop: 0}, 500);

<% if @education.errors.blank? %>
  $('#educations_tab').html('<%=j render partial: 'educations/index' %>');
<% end %>

app/views/educations/destroy.js.erb
$('#educations_tab').html('<%=j render partial: 'educations/index' %>');

app/views/educations/edit.js.erb
$('#education-form-container').html('<%=j render partial: 'educations/form', locals: {education: @education} %>');
$('#add-new-education').hide();

$("html, body").animate({ scrollTop: $('#education-form-container').offset().top }, 1000);

$(".date-picker").datepicker({
    dateFormat: "dd-mm-yy",
    maxDate: 0,
    yearRange: '1970:'+(new Date).getFullYear(),
    changeMonth: true,
    changeYear: true,
    showOtherMonths: true,
    selectOtherMonths: true
});
$("[rel='tooltip']").tooltip();

app/views/educations/new.js.erb
$('#education-form-container').html('<%=j render partial: 'educations/form', locals: {education: @education} %>');
$('#add-new-education').hide();

$(".date-picker").datepicker({
    dateFormat: "dd-mm-yy",
    maxDate: 0,
    changeMonth: true,
    changeYear: true,
    showOtherMonths: true,
    selectOtherMonths: true
});
$("[rel='tooltip']").tooltip();

app/views/educations/update.js.erb
$('#educations_tab').html('<%=j render partial: 'educations/index' %>');